// Every template shown in the gallery and editor. `isNew` marks the ones added for the builder.
export const templates = [
    { id: 'modern-blue',
        label: 'Modern Blue',
        isNew: true },
    { id: 'classic',
        label: 'Classic',
        isNew: true },
    { id: 'executive',
        label: 'Executive',
        isNew: true },
    { id: 'minimal',
        label: 'Minimal',
        isNew: true },
    { id: 'timeline',
        label: 'Timeline',
        isNew: true },
    { id: 'two-tone',
        label: 'Two Tone',
        isNew: true },
    { id: 'elegant-serif',
        label: 'Elegant Serif',
        isNew: true },
    { id: 'compact',
        label: 'Compact',
        isNew: true },
    { id: 'bold-header',
        label: 'Bold Header',
        isNew: true },
    { id: 'tech-dark',
        label: 'Tech Dark',
        isNew: true },
    { id: 'material-dark',
        label: 'Material Dark' },
    { id: 'material-dark-projects',
        label: 'Material Dark + Projects' },
    { id: 'left-right',
        label: 'Left Right' },
    { id: 'left-right-projects',
        label: 'Left Right + Projects' },
    { id: 'oblique',
        label: 'Oblique' },
    { id: 'oblique-projects',
        label: 'Oblique + Projects' },
    { id: 'side-bar',
        label: 'Side Bar' },
    { id: 'side-bar-projects',
        label: 'Side Bar + Projects' },
    { id: 'purple',
        label: 'Purple' },
    { id: 'creative',
        label: 'Creative' },
    { id: 'cool',
        label: 'Cool' },
    { id: 'green',
        label: 'Green' },
    { id: 'left-right-rtl',
        label: 'Left Right (RTL)' },
    { id: 'oblique-rtl',
        label: 'Oblique (RTL)' },
    { id: 'side-bar-rtl',
        label: 'Side Bar (RTL)' },
    { id: 'cool-rtl',
        label: 'Cool (RTL)' },
    { id: 'cool-rtl2',
        label: 'Cool 2 (RTL)' }
];
